version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: xrulescu-influxdb_server_1
      APP_PORT: 8086
      PROXY_AUTH_ADD: "false"

  server:
    image: influxdb:2.7.1
    user: "1000:1000"
    volumes:
      # Make sure your local config directory exists-
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped